### ISSUE TITLE
Store Data

### ISSUE THREAD

**Issue by kluthe** [rwart/Kanban-Organizer-with-persistence#1]
Hi! 
Super easy Kanban. No complicated stuff. Works great. 
How can you store the data? 

Kind regards,
Fred

**Comment by rwart** [comment]
Thanks Fred.
I am working to make it persistent with dedicated REST back-end. 
Greetings
Rafal

**Comment by kluthe** [comment]
👍

**Comment by rwart** [comment]
Fred, @kluthe 
Now with persistence.
Greetings
Rafal
